version: '3.4'

services:
  productmanagement.presentation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
    image: productmanagement
    container_name: ProductManagementAPI
    build:
      context: .
      args:
      - BUILD_CONFIGURATION=Development
      dockerfile: ProductManagement.Presentation/Dockerfile
      # dockerfile: UMDockerfile
    ports:
    -  "5001:5001"
