version: '3.4'

services:
  productmanagement.presentation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5001
    image: productmanagement
    container_name: ProductManagementAPI
    build:
      context: .
      args:
      - BUILD_CONFIGURATION=Development
      dockerfile: ProductManagement.Presentation/Dockerfile
      # dockerfile: UMDockerfile
    ports:
    -  "5001:5001"
    
  mssql-server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql-server
    environment:
        ACCEPT_EULA: Y
        SA_PASSWORD: SecretPassword123
    volumes:
        - ./sqlserver/data:/var/opt/mssql/data
        - ./sqlserver/log:/var/opt/mssql/log
    ports: 
        - "1433:1433"