version: '3.4'

services:
  usermanagement.presentation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5002
    image: usermanagement
    container_name: UserManagementAPI
    build:
      context: .
      args:
      - BUILD_CONFIGURATION=Development
      dockerfile: UserManagement.Presentation/Dockerfile
      # dockerfile: UMDockerfile
    ports:
    -  "5002:5002"
